name: gym
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - certifi=2018.8.24
  - ffmpeg=4.3.1
  - blas=1.0
  - cffi=1.11.5
  - cudatoolkit=10.2.89
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - intel-openmp=2020.2
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - ninja=1.8.2
  - numpy=1.14.2
  - olefile=0.46
  - pillow=5.2.0
  - pip=10.0.1
  - pycparser=2.20
  - python=3.5.6
  - setuptools=40.2.0
  - tk=8.6.10
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pytorch=1.5.1
  - pytorch-cpu=1.1.0
  - torchvision=0.6.1
  - pip:
    - absl-py==0.11.0
    - astor==0.8.1
    - atari-py==0.2.6
    - chardet==3.0.4
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.34.0
    - gym==0.17.3
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.1.1
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.1.0
    - markdown==3.2.2
    - matplotlib==3.0.3
    - opencv-python==4.4.0.42
    - opt-einsum==3.3.0
    - pandas==0.25.3
    - protobuf==3.14.0
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - requests==2.25.0
    - scipy==1.4.1
    - six==1.15.0
    - stable-baselines==2.10.2a0
    - tensorboard==1.15.0
    - tensorflow==1.15.4
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - torch==1.5.1
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==1.2.0